---
apiVersion: getambassador.io/v2
kind: ConsulResolver
metadata:
  name: consul-dev
spec:
  address:   "${HOST_IP}"
#  address:   consul-consul-server.default.svc.cluster.local:8501
  datacenter: dev
