apiVersion: v1
kind: Service
metadata:
  name: static-service
  annotations:
  getambassador.io/config: |
    ---
    apiVersion: ambassador/v1
    kind: TLSContext
    name: ambassador-consul
    hosts: []
    secret: ambassador-consul-connect
    ---
    apiVersion: ambassador/v1
    kind:  Mapping
    name:  static-service_mapping
    prefix: /echo/
    tls: ambassador-consul
    service: https://static-server:443
spec:
  type: NodePort
  selector:
  app: http-echo
  ports:
    - port: 443
  name: https-echo
  targetPort: 20000
