---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: qotm-tls
spec:
  prefix: /qotm-consul-tls/
  service: qotm-sidecar-proxy
  resolver: consul-dev
  tls: svcop-context
  load_balancer:
    policy: round_robin
