---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: qotm-tls
spec:
  prefix: /qotm/
  service: qotm
  resolver: consul-dev
  tls: consul-consul-server-cert #ambassador-consul
  load_balancer:
    policy: round_robin
